spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: sit
---
spring:
  profiles: dev
server:
  port: 8082
---
spring:
  profiles: prod
server:
  port: 8083

person:
  name: zl
  age: 22
  birth: 2018/10/31
  map: {k1: v1,k2: v2}
  list:
    - leis
    - zhanglei
  dog:
    name: 二哈
    age: 2
password: zh199609!

